### ISSUE TITLE
[question] How to decrease time of electing  a new leader?

### ISSUE THREAD

**Issue by lukaszkorecki** [allegro/consul-recipes#8]
Hi! Thank you for open sourcing this project. 

I've created a Clojure wrapper around the Leader Election parts - everything is working great so far during my initial testing. One thing that I'm not sure how to change  though is how long it takes to elect a new leader in a 3 node group when the leader is terminated. Currently it takes ~2 minutes for the election process to happen. 
For most of our use cases that's ok, but there's a couple of scenarios where 2 minutes is way too long.

How would you go about this? Do I have to create my  own instance  of Session class which sets a really short session expiry (10s?)?

Thanks!

**Comment by chemicL** [comment]
Hi Łukasz,

Please have a look at https://github.com/allegro/consul-recipes/blob/master/src/main/java/pl/allegro/tech/discovery/consul/recipes/session/Session.java#L204

It sets the TTL of the Session to 60 seconds, plus there's a 15s delay for acquiring a new session (look for `lock-delay` at https://www.consul.io/docs/internals/sessions.html for more info).

The Session is checked every 58 seconds (https://github.com/allegro/consul-recipes/blob/master/src/main/java/pl/allegro/tech/discovery/consul/recipes/session/Session.java#L31 and https://github.com/allegro/consul-recipes/blob/master/src/main/java/pl/allegro/tech/discovery/consul/recipes/session/Session.java#L56) and this can be adjusted.

All of these parameters are configurable, so it's up to you to find a middle ground between responsiveness to change and overloading your consul cluster with session queries.

This is a best effort approach and there are better solutions based on watches, however we went for simplicity as it works well in our use case. Please feel free to submit a PR if you find the need for a higher accuracy. We will definitely review it if you do.

Let us know if you have any other questions and thank you for your kind words.

**Comment by lukaszkorecki** [comment]
@chemicL Awesome, got it - that's really helpful. Can't think of a PR yet since all the capabilities are there, maybe with a code example on how to setup a leader elector with a shorter session expiry 👍
